- name: Make sure ceph list file exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/ceph.list
    owner: root
    group: root
    mode: "0644"
    state: touch

- name: Remove Ceph Quincy enterprise repository
  register: pve_apt_ceph_enterprise
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    line: deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
    state: absent

- name: Add Ceph Quincy no-subscription repository
  register: pve_apt_ceph_no_sub
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: "^deb http://download.proxmox.com/debian/ceph-quincy.*"
    line: deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
    state: present
