- name: Remove enteprise repository
  register: pve_apt_enterprise
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Get Debian version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      grep 'VERSION=' /etc/os-release | grep -Eo '[a-z]+'
  args:
    executable: /bin/bash
  register: debver
  changed_when: false

- name: Add free (no-subscription) repository
  register: pve_apt_nosub
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
    owner: root
    group: root
    mode: "0640"
    content: |
      deb http://download.proxmox.com/debian/pve {{ debver.stdout }} pve-no-subscription

- name: APT update
  when: pve_apt_enterprise.changed or pve_apt_nosub.changed
  ansible.builtin.apt:
    update_cache: true