- name: Get Debian version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      grep 'VERSION=' /etc/os-release | grep -Eo '[a-z]+'
  args:
    executable: /bin/bash
  register: debver
  changed_when: false

- name: Configure pve repositories
  ansible.builtin.include_tasks:
    file: pve.yaml

- name: Configure ceph repositories
  ansible.builtin.include_tasks:
    file: ceph.yaml

- name: APT update
  when: pve_apt_enterprise.changed or pve_apt_nosub.changed or pve_apt_ceph_enterprise.changed or pve_apt_ceph_no_sub.changed
  ansible.builtin.apt:
    update_cache: true
