- name: Install required python packages
  ansible.builtin.package:
    name:
      - python3-proxmoxer
    state: present

- name: Get local storage info
  community.general.proxmox_storage_info:
    api_user: "{{ pve_local_storage_api_user }}"
    api_password: "{{ pve_local_storage_api_password }}"
    api_host: 127.0.0.1
    name: local
  register: pve_local_storage_info

- name: Configure snippets storage
  ansible.builtin.include_tasks:
    file: snippets.yml

- name: Set local storage path to facts
  ansible.builtin.set_fact:
    pve_local_storage_path: "{{ pve_local_storage_info.proxmox_storages[0].path }}"
