- name: Add snippets to storage contents
  when: not 'snippets' in pve_local_storage_info.proxmox_storages[0].content
  ansible.builtin.lineinfile:
    path: /etc/pve/storage.cfg
    create: false
    firstmatch: true
    insertafter: "^\\W*dir:\\W*local$"
    regex: "^\\W*content\\W*(.*)$"
    line: "        content {{ (pve_local_storage_info.proxmox_storages[0].content + ['snippets']) | join(',') }}"

- name: Create snippets directory
  ansible.builtin.file:
    path: "{{ pve_local_storage_info.proxmox_storages[0].path }}/snippets"
    state: directory
    owner: root
    group: root
    mode: "0750"
