namespace: homecentr
name: proxmox
version: 1.1.0
readme: README.md

authors:
  - Lukas Holota <me@lholota.com>

description: Ansible roles used for proxmox nodes in my homelab

license:
  - MIT

tags:
  - linux
  - tools
  - infrastructure
  - proxmox

# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies: {}

repository: https://github.com/homecentr/ansible-collection-proxmox

# The URL to any online docs
documentation: https://docs.homecentr.one

build_ignore: []
