- name: "Set up port redirect (443 -> 8006)"
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: "{{ ansible_host }}" # To avoid collision with other services exposing the same port on a different ip
    destination_port: 443
    to_ports: 8006
    jump: REDIRECT
    comment: "Enable Proxmox admin interface on 443"
    in_interface: vmbr0 # Must be specified to prevent docker containers calling 443 to be redirected to local

- name: "Get serialized rule for permanent storage"
  register: pve_https_forward_iptables_rule
  changed_when: false
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      iptables-save -t nat | grep 'Proxmox'

- name: Create iptables directory
  ansible.builtin.file:
    path: /etc/iptables
    state: directory
    owner: root
    group: root
    mode: "0640"

- name: "Save iptables state to a file"
  ansible.builtin.copy:
    dest: /etc/iptables/nat.rules.v4
    owner: root
    group: root
    mode: "0644"
    content: |
      *nat
      {{ pve_https_forward_iptables_rule.stdout_lines[0] }}
      COMMIT

- name: "Create iptables restore script"
  ansible.builtin.copy:
    dest: /etc/network/if-up.d/run-iptables
    mode: "0700"
    owner: root
    group: root
    content: |
      #!/bin/sh
      iptables-restore -n < /etc/iptables/nat.rules.v4
      # Avoid duplicate rules
      iptables-save | uniq | iptables-restore
