- name: "Set up port redirect (443 -> 8006)"
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: 443
    to_ports: 8006
    source: "{{ ansible_host }}" # To avoid collision with other services exposing the same port on a different ip
    jump: REDIRECT
    comment: "Enable Proxmox admin interface on 443"
    in_interface: vmbr0 # Must be specified to prevent docker containers calling 443 to be redirected to local

- name: "Get serialized rule for permanent storage"
  register: pve_https_forward_iptables_rule
  ansible.builtin.shell:
    cmd: "iptables-save -t nat | grep 'Proxmox'"

- name: "Save iptables state to a file"
  ansible.builtin.lineinfile:
    path: /etc/iptables/nat.rules.v4
    regex: '^(.*)Proxmox admin interface(.*)$'
    line: "{{ pve_https_forward_iptables_rule.stdout_lines[0] }}"
    state: present

- name: "Create iptables restore script"
  ansible.builtin.copy:
    dest: /etc/network/if-up.d/run-iptables
    mode: "0700"
    owner: root
    group: root
    content: |
      #!/bin/sh
      iptables-restore < /etc/iptables/nat.rules.v4
